name: r_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-optparse
  - r-data.table
  - r-fs
  - r-stringr
  - r-dplyr
  - r-ggplot2
  - r-readr
  - r-glue
  - bioconductor-rsamtools
  - samtools
