# Parameters for snakemake run

#input_file: "/central/scratch/clarayu/enterobacteriaceae_meta_study_paper_samples.tsv" # Input TSV file with list of run accessions in first column and study accessions in 2nd column

#output_fastq_dir: "/central/scratch/clarayu/nature_fastqs/" # Output directory to store cleaned FASTQs

#host_ref: "/central/groups/MazmanianLab/clara/microbiome_sample_search/metagen-paladin/chm13v2.0.fa" # FASTA file of host genome for decontamination

#fasta_dir: "/central/groups/MazmanianLab/clara/microbiome_sample_search/data/input/" # Directory with fasta file

#output_align_dir: "/central/scratch/clarayu/align_output/" # Directory for alignment files

#fasta_path: "/central/groups/MazmanianLab/clara/microbiome_sample_search/data/input/hCom2/hCom2.fasta.txt" #fasta file name

#paladin_ref_dir: "/central/groups/MazmanianLab/clara/microbiome_sample_search/metagen-paladin"

#paladin:
#  cores: 6

# Parameters for snakemake run

#Path to input TSV file with list of run accessions in first column and study accessions in 2nd column
# input_file: /central/groups/MazmanianLab/joeB/git/metagen-paladin/test/input.tsv
# input_file: /central/groups/MazmanianLab/joeB/Microbiota-Immunomodulation/Microbiota-Immunomodulation/data/input/global_metagenome_screen/enterobacteriaceae_meta_study_paper_samples.tsv
# input_file: /central/groups/MazmanianLab/joeB/Microbiota-Immunomodulation/Microbiota-Immunomodulation/data/input/global_metagenome_screen/subset.tsv
# input_file: /central/scratch/clarayu/enterobacteriaceae_meta_study_paper_samples_full.tsv
input_file: /resnick/groups/MazmanianLab/clarayu/microbiome_sample_search/data/interim/aggregate_metadata/nature_enriched_run_study_filtered_completed.tsv

#Output directory to store cleaned FASTQs
output_fastq_dir: /resnick/scratch/clarayu/new_1k_run/fastqs/
#output_fastq_dir: /resnick/groups/MazmanianLab/clarayu/full_run/fastqs/
# output_fastq_dir: /central/scratch/jbok/metagen-paladin_testmeagain/output_fastq/

#Output directory to store final summary TSVs
output_summary_dir: /resnick/groups/MazmanianLab/clarayu/microbiome_sample_search/new_1k_run_summary/

#Path to FASTA file of host genome for decontamination
host_ref: /resnick/groups/MazmanianLab/clarayu/microbiome_sample_search/metagen-paladin/chm13v2.0.fa

# path to fasta file to use for alignment
fasta_path: /resnick/groups/MazmanianLab/clarayu/microbiome_sample_search/data/input/hCom2/hCom2.fasta

# path to where paladin reference fasta file will be stored
paladin_ref_dir: /resnick/scratch/clarayu/new_1k_run/paladin_ref/

logfile_name: new_1k_run

paladin:
  cores: 8